### ISSUE TITLE
Wrong name for key qrda-i

### ISSUE THREAD

**Issue by p9g** [HL7/JIRA-Spec-Artifacts#84]
https://github.com/HL7/JIRA-Spec-Artifacts/blob/master/xml/SPECS-CDA.xml has
`<specification key="qrda-i" deprecated="false" name="HL7 CDA® R2 Implementation Guide: Supplemental QRDA Clinical Quality Data Sharing User Guide, Release 1"/>` 
which corresponds to http://www.hl7.org/implement/standards/product_brief.cfm?product_id=477 which is **NOT** the QRDA Category I spec.
QRDA Category I corresponds to http://www.hl7.org/implement/standards/product_brief.cfm?product_id=35 with the title "HL7 CDA® R2 Implementation Guide: Quality Reporting Document Architecture - Category I (QRDA I) - US Realm"

Keep key `qrda-i` but change the name: 
`<specification key="qrda-i" deprecated="false" name="HL7 CDA® R2 Implementation Guide: Quality Reporting Document Architecture - Category I (QRDA I) - US Realm"/>`

CQI WG will review current state of the "Supplemental" doc, which is informative. If we need to add that spec we will pick a different "key" for it.

**Comment by lmckenzi** [comment]
Please submit a pull request to address.

**Comment by p9g** [comment]
Added PR https://github.com/HL7/JIRA-Spec-Artifacts/pull/85
